In [1]:
import numpy as np
from scipy import stats

/Users/jun/.pyenv/versions/miniconda3-latest/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [2]:
def create_toy_data():
    x1 = np.random.normal(size=(100, 2))
    x1 += np.array([-5, -5])
    x2 = np.random.normal(size=(100, 2))
    x2 += np.array([5, -5])
    x3 = np.random.normal(size=(100, 2))
    x3 += np.array([0, 5])
    return np.vstack((x1, x2, x3))


In [4]:
X = create_toy_data()

In [22]:
n_components = 10
n_samples = X.shape[0]

In [23]:
n_samples / n_components + np.zeros(n_components)

array([30., 30., 30., 30., 30., 30., 30., 30., 30., 30.])

In [34]:
m = X[np.random.choice(n_samples, n_components, replace=False)].T

In [40]:
d = X[:,:,None] - m
d.shape

(300, 2, 10)

In [37]:
m.shape

(2, 10)

In [38]:
X.shape

(300, 2)

In [39]:
X[:,:,None].shape

(300, 2, 1)

In [53]:
x = np.array([1,2,3])

In [56]:
y = np.array([30,22,13])

In [57]:
np.outer(x, y)

array([[30, 22, 13],
       [60, 44, 26],
       [90, 66, 39]])

In [58]:
np.outer(y,x)

array([[30, 60, 90],
       [22, 44, 66],
       [13, 26, 39]])